import inquirer from "inquirer";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { ok, info, bold, warn } from "../utils/colors.js";

function isValidHttpsUrl(input) {
  try {
    const url = new URL(input);
    return url.protocol === "https:" || "URL must start with https://";
  } catch {
    return "Please enter a valid URL (e.g. https://example.com)";
  }
}

function generateDockerCompose({ siteUrl, port, crawlInterval, maxPages, webhookSecret }) {
  const envLines = [
    `      - SITE_URL=${siteUrl}`,
    `      - CRAWL_INTERVAL=${crawlInterval * 60}`,
    `      - MAX_PAGES=${maxPages}`,
    `      - PORT=8080`,
    `      - EMBEDDING_MODEL=all-MiniLM-L6-v2`,
  ];
  if (webhookSecret) {
    envLines.push(`      - OPENFEEDER_WEBHOOK_SECRET=${webhookSecret}`);
  }

  return `# OpenFeeder Sidecar — generated by openfeeder setup
services:
  openfeeder:
    image: ghcr.io/openfeeder/sidecar:latest
    ports:
      - "${port}:8080"
    environment:
${envLines.join("\n")}
    volumes:
      - openfeeder_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8080/healthz').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  openfeeder_data:
`;
}

function generateCaddySnippet(siteUrl, port) {
  const { hostname } = new URL(siteUrl);
  return `# Add this to your Caddyfile for ${hostname}:
${hostname} {
    handle /.well-known/openfeeder.json {
        reverse_proxy localhost:${port}
    }
    handle /openfeeder* {
        reverse_proxy localhost:${port}
    }
    # ... your existing site config
}`;
}

export async function setup() {
  console.log(bold("\n🔧 OpenFeeder Setup Wizard\n"));

  const answers = await inquirer.prompt([
    {
      type: "input",
      name: "siteUrl",
      message: "Site URL:",
      validate: isValidHttpsUrl,
    },
    {
      type: "number",
      name: "port",
      message: "Sidecar port:",
      default: 8080,
    },
    {
      type: "number",
      name: "crawlInterval",
      message: "Crawl interval (minutes):",
      default: 60,
    },
    {
      type: "number",
      name: "maxPages",
      message: "Max pages to crawl:",
      default: 500,
    },
    {
      type: "input",
      name: "webhookSecret",
      message: "Webhook secret (leave blank to skip):",
      default: "",
    },
  ]);

  // Generate docker-compose.yml
  const compose = generateDockerCompose(answers);
  const composePath = path.resolve("docker-compose.yml");
  await writeFile(composePath, compose);
  console.log(ok(`\n✅ Generated ${composePath}`));

  // Generate .env file
  const envContent = [
    `SITE_URL=${answers.siteUrl}`,
    `PORT=${answers.port}`,
    `CRAWL_INTERVAL=${answers.crawlInterval * 60}`,
    `MAX_PAGES=${answers.maxPages}`,
  ];
  if (answers.webhookSecret) {
    envContent.push(`OPENFEEDER_WEBHOOK_SECRET=${answers.webhookSecret}`);
  }
  const envPath = path.resolve(".env");
  await writeFile(envPath, envContent.join("\n") + "\n");
  console.log(ok(`✅ Generated ${envPath}`));

  // Print Caddy config
  console.log(info("\n📋 Caddy config snippet (add to your Caddyfile):\n"));
  console.log(generateCaddySnippet(answers.siteUrl, answers.port));

  // Next steps
  console.log(bold("\n📌 Next steps:\n"));
  console.log(`  1. ${info("docker compose up -d")}`);
  console.log(`  2. ${info("openfeeder status")}`);
  console.log(`  3. Add the Caddy snippet above to your Caddyfile`);
  console.log(`  4. ${info("caddy reload")}\n`);

  if (!answers.webhookSecret) {
    console.log(warn("⚠️  No webhook secret set — anyone can trigger content updates."));
    console.log(warn("   Set one later: openfeeder config set OPENFEEDER_WEBHOOK_SECRET <secret>\n"));
  }
}
